name: Deploy AutoFilter Extension

on:
  push:
    branches:
      - master
    paths:
      - 'xExtension-AutoFilter/**'
  #workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare directory permissions
        run: |
          # Делаем пользователя dt владельцем, группу оставляем www-data
          sudo chown -R dt:www-data /srv/freshrss/extensions/xExtension-AutoFilter
          # Даем полные права владельцу и группе, чтение остальным
          sudo chmod -R 775 /srv/freshrss/extensions/xExtension-AutoFilter

      - name: Sync extension files
        run: |
          rsync -av --no-owner --no-group --delete \
            ./xExtension-AutoFilter/ \
            /srv/freshrss/extensions/xExtension-AutoFilter/

      - name: Restart FreshRSS container
        run: |
          sudo docker restart freshrss

      - name: Verify deployment
        run: |
          sleep 5
          docker logs freshrss --tail 20
